################# REGISTRY #####################################

apiVersion: apps/v1           
kind: Deployment              
metadata:
  name: registry    
  labels:                     
    app: app-covid
spec:
  replicas: 1                 
  selector:
    matchLabels:          
      app: "app-covid"
  template:                   
    metadata:
      labels:                 
        app: app-covid
    spec:                     
      containers:
      - name: registry
        image: kbenito/registry
        imagePullPolicy: Always
        ports:
          - name: http
            containerPort: 8761 
---

apiVersion: v1                
kind: Service                 
metadata:                     
  name: registry    
  labels:                     
    app: app-covid
spec:                         
  type: NodePort              
  selector:
    app: app-covid   
  ports:                      
  - name: http
    port: 8761
    targetPort: 8761
    
---

####################### COVID SERVICE ############################

apiVersion: apps/v1           
kind: Deployment              
metadata:
  name: covid-service    
  labels:                     
    app: app-covid
spec:
  replicas: 1                 
  selector:
    matchLabels:          
      app: "app-covid"
  template:                   
    metadata:
      labels:                 
        app: app-covid
    spec:                     
      containers:
      - name: covid-service
        image: kbenito/covid-service
        imagePullPolicy: Always
        env:
            - name: URL_REGISTRY
              value: registry.default.svc.cluster.local
        ports:
          - name: http
            containerPort: 8085 
---
apiVersion: v1                
kind: Service                 
metadata:                     
  name: covid-service    
  labels:                     
    app: app-covid
spec:                         
  type: NodePort              
  selector:
    app: app-covid   
  ports:                      
  - name: http
    port: 8085
    targetPort: 8085

---
################################### GATEWAY #####################


apiVersion: apps/v1           
kind: Deployment              
metadata:
  name: gateway    
  labels:                     
    app: app-covid
spec:
  replicas: 1                
  selector:
    matchLabels:          
      app: "app-covid"
  template:                   
    metadata:
      labels:                 
        app: app-covid
    spec:                     
      containers:
      - name: gateway
        image: kbenito/gateway
        imagePullPolicy: Always
        env:
            - name: URL_REGISTRY
              value: registry.default.svc.cluster.local
        ports:
          - name: http
            containerPort: 8080 
---
apiVersion: v1                
kind: Service                 
metadata:                     
  name: gateway    
  labels:                     
    app: app-covid
spec:                         
  type: NodePort              
  selector:
    app: app-covid   
  ports:                      
  - name: http
    port: 8080
    targetPort: 8080

---

#########################################  FRONTEND ANGULAR##################

apiVersion: apps/v1           
kind: Deployment              
metadata:
  name: frontend-angular    
  labels:                     
    app: app-covid
spec:
  replicas: 1                 
  selector:
    matchLabels:          
      app: "app-covid"
  template:                   
    metadata:
      labels:                 
        app: app-covid
    spec:                     
      containers:
      - name: frontend-angular
        image: kbenito/frontend-angular
        imagePullPolicy: Always
        ports:
          - name: http
            containerPort: 4200 
---
apiVersion: v1                
kind: Service                 
metadata:                     
  name: frontend-angular    
  labels:                     
    app: app-covid
spec:                         
  type: NodePort              
  selector:
    app: app-covid   
  ports:                      
  - name: http
    port: 4200
    targetPort: 4200