server:
  port: 8080

spring:
  application:
    name : gateway-authentication
  cloud:
    discovery:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://${URL_REGISTRY}:8761/eureka
  instance:
    prefer-ip-address: true    
zuul:
  routes:
    covid:
      path: /covid/**
      service-id: covid-service
